name: TFsec check
on:
  push:
    branches:
      - dev
jobs:
  check_tfsec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf-vulnerable

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup tfsec
        run: wget https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64 -O tfsec && chmod +x tfsec

      - name: Static check infrastructure
        run: ./tfsec --force-all-dirs  
